version: '3'

services:
  db:
    hostname: postgres-db
    restart: always
    image: 'postgres:latest'
    env_file:
      - "db.env"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "3001:5432"